config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/appointments/new_all_workouts', to: 'appointments#new_all_workouts', as: 'new_all_workouts'
  post '/appointments', to: 'appointments#create_all_workouts', as: 'create_all_workouts'
  resources :appointments
  resources :stats
  resources :users
  resources :exercises
  resources :workouts

  delete '/sessions/logout', to: 'sessions#logout', as: 'logout'
  get '/sessions/new', to: 'sessions#new', as: 'new_login'
  post '/sessions', to: 'sessions#create', as: 'login'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/workout.rb
class Workout < ApplicationRecord
    belongs_to :user 
    has_many :exercise_workouts
    has_many :appointments
    has_many :exercises, through: :exercise_workouts 
    has_many :users, through: :appointments 

    validates :kind, :user_id, presence: true

    accepts_nested_attributes_for :exercise_workouts, allow_destroy: true

    def self.sorted
        self.all.sort_by {|wo| wo.kind }
    end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
    skip_before_action :authorization, only: [:index]
    before_action :set_workout, only: [:show, :edit, :update, :destroy]

    def index
        #  byebug
        @workouts = Workout.all 
        render :index
    end

    def show
        render :show 
    end

    def new
        @workout = Workout.new  
        5.times do 
            @workout.exercise_workouts.build 
        end
        if params[:legs]
            @exercises = Exercise.where(category: "Legs")
        elsif params[:arms]
            @exercises = Exercise.where(category: "Arms/Shoulders")
        elsif params[:olympic]
            @exercises = Exercise.where(category: "Olympic Weightlifting")
        elsif params[:chest]
            @exercises = Exercise.where(category: "Chest")
        elsif params[:back]
            @exercises = Exercise.where(category: "Back")
        elsif params[:all]
            @exercises = Exercise.all
        else 
            @exercises = Exercise.all  
        end

        render :new 
    end

    def create
        workout = Workout.create(workout_params)
        if workout.valid?
            redirect_to new_appointment_path
        else
            flash[:errors] = workout.errors.full_messages
            redirect_to new_workout_path
        end
    end

    def edit
        render :edit 
    end

    def update
        if @workout.update(workout_params)
            redirect_to workout_path(@workout)
        else
            flash[:errors] = @workout.errors.full_messages
            redirect_to edit_workout_path
        end
    end

    def destroy
        @workout.destroy 
        redirect_to workouts_path
    end

    private

    def workout_params
        params.require(:workout).permit(:date, :time, :kind, :user_id, exercise_workouts_attributes: [:sets, :reps, :exercise_id, :workout_id, :_destroy])
    end

    def set_workout
        @workout = Workout.find(params[:id])
    end
end

app/views/workouts/_form.html.erb
<% if flash[:errors]%>
<% flash[:errors].each do |error|%>
<p style="color:red;"><%= error %> <br>
<% end%>
<% end%>


<div class="form-container">
<div class="btn-group">
<%= form_tag new_workout_path, method: :get do %>
    <%= submit_tag "Olympic Weightlifting", name: :olympic, :class => 'form-buttons'%>
<% end %>
<%= form_tag new_workout_path, method: :get do %>
    <%= submit_tag "Arms/Shoulders", name: :arms, :class => 'form-buttons'%>
<% end %>
<%= form_tag new_workout_path, method: :get do %>
    <%= submit_tag "Legs", name: :legs, :class => 'form-buttons'%>
<% end %>
<%= form_tag new_workout_path, method: :get do %>
    <%= submit_tag "Chest", name: :chest, :class => 'form-buttons'%>
<% end %>
<%= form_tag new_workout_path, method: :get do %>
    <%= submit_tag "Back", name: :back, :class => 'form-buttons'%>
<% end %>
<%= form_tag new_workout_path, method: :get do %>
    <%= submit_tag "All", name: :all, :class => 'form-buttons'%>
<% end %>
</div>
<br>
<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <%= error %>
    <% end %>
<% end %>
<%= form_for @workout do |f| %>
<div class="form-input">
     <%= f.hidden_field :user_id, value: session[:user_id] %><br> 
    <%= f.label "Title" %>
    <%= f.text_field :kind %><br><br>
    
    <%= f.fields_for :exercise_workouts do |f| %>
        <%= f.label :exercise_id %>
        <%= f.collection_select :exercise_id, @exercises, :id, :name, prompt: true%>
        <%= f.label :sets %>
        <%= f.number_field :sets %>
        <%= f.label :reps %>
        <%= f.number_field :reps %>
        <%= f.check_box :_destroy %>Delete<br><br>
    <% end %>
    </div>
    <%= f.submit :class => 'form-buttons' %>
<% end %><br><br>
</div>

app/views/workouts/edit.html.erb
<h1>Edit <%= @workout.kind %>Workout</h1>

<%= render 'form'%>

app/views/workouts/index.html.erb
<h1>Workouts</h1>


<%= image_tag "strong.jpg", class: "exercises-img" %>
<p>(Click workout to view details)</p>
<div class="index-container">

<div class="index-tile", style="margin-left: 200 px; top: 400px; left: 215px;">
<h3><u>Existing Workouts</u></h3>
<% @workouts.sorted.each do |workout| %>
    <% if workout.user_id != @current_user %>
    <p><h3><%= link_to workout.kind, workout_path(workout)%></h3></p>
    <% end %>
<% end %>
</div>

<div class="index-tile", style="margin-right:200 px; top: 400px; right: 215px;">
<h3><u>Your Workouts</u></h3>
<% @workouts.select do |workout| %>
    <% if workout.user_id == session[:user_id] %>
    <p><h3><%= link_to workout.kind, workout_path(workout)%></h3></p>
    <% end %>
<% end %>
</div>
</div>

app/views/workouts/new.html.erb
<h1>Create New Workout</h1>

<%= render 'form'%>

app/views/workouts/show.html.erb
<div class="container"><h1><%= @workout.kind %></h1>

<h3>Created By: <%= link_to @workout.user.name, user_path(@workout.user) %></h3>

<h3>Exercises:</h3>
</div>
<% @workout.exercises.each do |x| %>
    <div class="container"><div class="showname"><%= link_to x.name, exercise_path(x) %></div><br>
    <%# move logic to model%>
    <div class = "wo-stats"><%= x.exercise_workouts.find {|join| join.workout == @workout}.sets %> sets x <%= x.exercise_workouts.find {|join| join.workout == @workout}.reps %> reps</strong><br><br>
    <i><%= x.description %></i><br>

<iframe width="764" height="573" src="http://www.youtube.com/embed/<%=x.video%>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> 
    </div></div><br><br>
<% end %>

<% if @current_user %>
<%= button_to "Schedule this Workout", new_all_workouts_path, method: :get, class: "form-buttons" %> <br><br>
<% end%>

<% if @current_user == @workout.user%>
<%= button_to "Edit Workout", edit_workout_path, method: :get, class: "form-buttons"%> <br><br>
<% end%>

<% if @current_user == @workout.user%>
<%= button_to "Delete Workout", workout_path(@workout), method: :delete, class: "form-buttons" %> <br>
<% end%>