config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/appointments/new_all_workouts', to: 'appointments#new_all_workouts', as: 'new_all_workouts'
  post '/appointments', to: 'appointments#create_all_workouts', as: 'create_all_workouts'
  resources :appointments
  resources :stats
  resources :users
  resources :exercises
  resources :workouts

  delete '/sessions/logout', to: 'sessions#logout', as: 'logout'
  get '/sessions/new', to: 'sessions#new', as: 'new_login'
  post '/sessions', to: 'sessions#create', as: 'login'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :stats
    has_many :appointments
    has_many :workouts
    has_many :workouts, through: :appointments
    has_many :exercises, through: :stats
    
    # validates :username, :password, :name, :age, :weight, :height, presence: true
    # validates :password, confirmation: { case_sensitive: true}
    # validates :username, uniqueness: true
    # validates :age, numericality: {greater_than: 0}

    has_secure_password
    has_one_attached :photo
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
     skip_before_action :authorization, only: [:new, :create]
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
        @appointments = @user.appointments
    end
    
    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.valid?
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
          flash[:user_errors] = @user.errors.full_messages
          redirect_to new_user_path
        end
    end

    def edit
        @user = User.find(params[:id])
  
    end
    
    def update
        @user = User.find(params[:id])
        @user.photo.attach(params[:photo])
        if @user.update(user_params)
          redirect_to user_path(@user)
        else
          flash[:user_errors] = @user.errors.full_messages
          redirect_to edit_user_path
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_path
    end

    private

    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation, :name, :age, :weight, :height, :photo)
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if flash[:user_errors]%>
    <% flash[:user_errors].each do |error|%>
        <p style="color:red;"><%= error %> <br>
    <% end%>
<% end%>

<div class="form-container">
<%= form_for @user do |f| %>
<div class="form-input">
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :username %>
<%= f.text_field :username %><br>
<%= f.label :age %>
<%= f.number_field :age %>
<%= f.label :weight %>
<%= f.number_field :weight %>
<%= f.label :height %>
<%= f.number_field :height %><br><br>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label "Confirm Password" %>
<%= f.password_field :password_confirmation %><br><br>
<%= f.label "Profile Photo" %>
<%= f.file_field :photo %>
</div>
<br><br>
<%= f.submit :class => "form-buttons" %>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit Your Profile:</h1>
<%= render "form" %>

app/views/users/index.html.erb
<h1>User List</h1>
<h3><% @users.each do |user|  %>
<%= link_to user.username, user_path(user) %> <br>
<% end%>
</h3>

app/views/users/new.html.erb
<h1>Join Us!</h1>
<%= render "form" %>

app/views/users/show.html.erb
<div class="show-container">
<div class="show-tile1">
<h1><%= @user.name%></h1>
<% if @user.photo.attached?%>
    <div class="profile-pic"><image src="<%= (url_for(@user.photo)) %>"></div>
<% end%>
<h3>Username: <%= @user.username %></h3>
<h3>Age: <%= @user.age %> years old</h3>
<h3>Height: <%= @user.height %> inches</h3>
<h3>Weight: <%= @user.weight %> pounds</h3>
<h4><%= button_to "Edit Profile", edit_user_path(@user), method: :get, class: "form-buttons" %></h4>
<h4><%= button_to "Log a PR!", new_stat_path, method: :get, class: "form-buttons"%></h4>
<h3>My Personal Records: </h3>
<h5> (Click exercise to view details)</h5>
<h4> <% @user.stats.each do |stat|%>
<%= link_to stat.exercise.name, stat_path(stat) %> @ <%= stat.weight%> lbs.  <br>
<% end%></h4>
<h3><%= button_to "Delete Account", user_path(@user), method: :delete, data: { confirm: "Are you sure? You will lose all your workouts and stats."}, class: "form-buttons"%></h3>
</div>

<div class="show-tile">
<h2>Scheduled Workouts</h2>
<%= month_calendar events: @appointments do |date, appointments| %>
  <%= date.strftime("%m/%d/%Y") %>

  <% appointments.each do |appointment| %>
    <div>
      Workout: <br>
      <%=link_to appointment.workout.kind, workout_path(appointment.workout) %> <br> @ <%= appointment.location%><br>
      <%= link_to appointment.parsed_time, appointment_path(appointment) %>
    </div>
  <% end %>
</div>
<% end %>
</div>