config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/appointments/new_all_workouts', to: 'appointments#new_all_workouts', as: 'new_all_workouts'
  post '/appointments', to: 'appointments#create_all_workouts', as: 'create_all_workouts'
  resources :appointments
  resources :stats
  resources :users
  resources :exercises
  resources :workouts

  delete '/sessions/logout', to: 'sessions#logout', as: 'logout'
  get '/sessions/new', to: 'sessions#new', as: 'new_login'
  post '/sessions', to: 'sessions#create', as: 'login'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/stat.rb
class Stat < ApplicationRecord
    belongs_to :user 
    belongs_to :exercise 

    validates :user_id, :exercise_id, :weight, :comment, presence: true

    has_one_attached :photo
    
    def self.stats_by_exercise
        self.all.sort_by {|stat| stat.exercise.name}
    end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
    def index
        @stats = Stat.all
    end

    def show
        
        @stat = Stat.find(params[:id])
    end
    
    def new
        @stat = Stat.new
    end

    def create
        @stat = Stat.create(stat_params)
        if @stat.valid?
          redirect_to stat_path(@stat)
        else
          flash[:stat_errors] = @stat.errors.full_messages
          redirect_to new_stat_path
        end
    end

    def edit
        @stat = Stat.find(params[:id])
    end
    
    def update
        @stat = Stat.find(params[:id])
        @stat.photo.attach(params[:photo])
        if @stat.update(stat_params)
          redirect_to stat_path(@stat)
        else
          flash[:stat_errors] = @stat.errors.full_messages
          redirect_to edit_stat_path
        end
    end

    def destroy
        @stat = Stat.find(params[:id])
        @stat.destroy
        redirect_to user_path(@stat.user)
    end

    private

    def stat_params
        params.require(:stat).permit(:user_id, :exercise_id, :weight, :time, :comment, :photo)
    end
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/stats/_form.html.erb
<% if flash[:stat_errors]%>
<% flash[:stat_errors].each do |error|%>
<p style="color:red;"><%= error %> <br>
<% end%>
<% end%>
<div class="form-container">
<div class="form-input">
<%= form_for @stat do |f| %>
 <%= f.hidden_field :user_id, value: session[:user_id] %> 
<%= f.label :exercise_id %>
<%= f.collection_select :exercise_id, Exercise.all, :id, :name, prompt: true %>
<%= f.label :weight %>
<%= f.number_field :weight %><br><br>
<%= f.label :comment %>
<%= f.text_field :comment %>
<%= f.label "Upload Photo" %>
<%= f.file_field :photo %></div><br>
<%= f.submit class: "form-buttons" %>
</div>
<% end %>
</div>

app/views/stats/edit.html.erb
<h1>Edit Personal Record:</h1>
<%= render "form" %>

app/views/stats/index.html.erb
<h1>We're Stronger Together!</h1>
<div class="stronggroup-img">
      <%= image_tag "stronggroup.jpeg", class: "stronggroup-img" %>
</div>
<h2>All Personal Records:</h2>

<% @stats.stats_by_exercise.each do  |st| %>
    <h4><%= link_to st.exercise.name, stat_path(st) %>: <%= st.weight %> lbs: <%= st.user.name %></h4>
<% end %>
</div>

app/views/stats/new.html.erb
<h1>Log a New Personal Record:</h1>
<%= render "form" %>
<br>


<div class="pr-img">
      <%= image_tag "PR.jpeg", class: "pr-img" %>
</div>

app/views/stats/show.html.erb
<br>
<div class="congrats-img">
      <%= image_tag "congrats.jpeg", class: "congrats-img" %>
</div>
<h1>You did great, <%= @stat.user.name %>!!!</h1>

<h3><%= link_to @stat.exercise.name, exercise_path(@stat.exercise) %></h3>
<h3><%= @stat.weight %> pounds!</h3>
<h3><%= @stat.comment %></h3>
<% if @stat.photo.attached?%>
    <div class="profile-pic"><image src="<%= (url_for(@stat.photo)) %>"></div>
<% end%>
    <br><br>
<%= button_to "Edit Stat", edit_stat_path(@stat), method: :get, class: "form-buttons" %> <br>
<%= button_to "Delete Stat", stat_path(@stat), method: :delete, class: "form-buttons"%> <br>
<%= button_to "View All Stats", stats_path, method: :get, class: "form-buttons" %> <br>
<%= button_to "Log another PR!", new_stat_path, method: :get, class: "form-buttons" %><br>