config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/appointments/new_all_workouts', to: 'appointments#new_all_workouts', as: 'new_all_workouts'
  post '/appointments', to: 'appointments#create_all_workouts', as: 'create_all_workouts'
  resources :appointments
  resources :stats
  resources :users
  resources :exercises
  resources :workouts

  delete '/sessions/logout', to: 'sessions#logout', as: 'logout'
  get '/sessions/new', to: 'sessions#new', as: 'new_login'
  post '/sessions', to: 'sessions#create', as: 'login'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FitnessApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="banner">
      <ul>
        <li class="center"><%= image_tag "Str.gif", class: "banner-img" %></li>
        <li class="left">Today's actions are tomorrow's...<br> results</li>
        <%# <li class="left"><%= button_to "Learn More", users_path, class: "form-buttons" %></li>
        <li class="right"><%= image_tag "fb-twitter-instagram.jpeg"%></li>
      </ul>
    </div>

    <ul class="nav">
      <li class="left"><%= link_to "Home", root_path %>
      <li class="left"><%= link_to "View Exercises", exercises_path %></li>
      <li class="left"><%= link_to "Create a Workout", new_workout_path %></li>
      <li class="left"><%= link_to "View Existing Workouts", workouts_path %></li>

      <% if @current_user %>
      
        <li class="right"><%= link_to "Log Out", logout_path, method: :delete %></li>
        <li class="right"><%= link_to "My Profile", user_path(@current_user) %></li>
        <li class="right">Welcome, <%= @current_user.name %>!</li>
      <% else %>
        <li class="right"><%= link_to "Login", new_login_path %></li>
        <li class="right"><%= link_to "Sign Up", new_user_path %></li>
      <% end %>
    </ul>
    <% if flash[:message]%>
    <p style="color:red;"><%= flash[:message] %>
    <% end%>
  <div class="container">
    <%= yield %>
    </div>
  </body>
</html>